 name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      
      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Set up .env file
        run: |
          echo "LOGIN_URL=${{ secrets.LOGIN_URL }}" > .env
          echo "ANOTHER_ENV=${{ secrets.ANOTHER_ENV }}" >> .env

      - name: Install dependencies and build the project
        run: |
          npm install
          npm run build dev --if-present

      # Store the dist folder as an artifact
      - name: Store the dist folder
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
      
      # You can add more steps here for deployment if needed
